### ISSUE TITLE
Published "module" in package.json should point to sources that are transpiled to ES5, except import statements 

### ISSUE THREAD

**Issue by kayneb** [funfix/funfix.js#113]
As per https://github.com/rollup/rollup/wiki/pkg.module, the `module` field should point to JS that maintains its import/export statements, but is transpiled to ES5 otherwise. Otherwise, any consumers that are using the module field in their build tools (like rollup or webpack when tree-shaking is enabled) must also transpile this dependency.

Generally, all libraries transpile down to ES5, except the module imports so as to not burden consumers.

**Comment by alexandru** [comment]
Discussed in https://github.com/funfix/funfix/pull/114 — will close this for now to keep the issue tracket clean 🙂 

If there are issues with the proposed solution, please open another ticket.
