### ISSUE TITLE
`mapN` is gone

### ISSUE THREAD

**Issue by OliverJAsh** [funfix/funfix.js#121]
Hi @alexandru 

When trying to upgrade I noticed `mapN` was gone, and I was curious what the reasoning behind this was?

Thanks,
Olly

**Comment by lostintime** [comment]
@OliverJAsh which class `mapN` are missing from? Those are still present at least for IO and Future (v7.0.1), dunno about others, didn't use them

  * https://github.com/funfix/funfix/blob/master/packages/funfix-exec/src/future.ts#L980
  * https://github.com/funfix/funfix/blob/master/packages/funfix-effect/src/eval.ts#L371

**UPD**: Sorry, I confused `mapN` with `map1` - `map6`

**Comment by lostintime** [comment]
It's probably the `Option` (v6.2.2: https://github.com/funfix/funfix/blob/v6.2.2/packages/funfix-core/src/disjunctions.ts#L652)

**Comment by alexandru** [comment]
I removed `mapN` because it's non-standard and it was less useful than I thought it is.

`Option` also has filter on it, so you can do ... `option.filter(_ != null)` and I find this one more intuitive.

If you have a good use case for it, I'm willing to add it back.

**Comment by alexandru** [comment]
Actually the use-case would be the one in the sample:

```scala
Option.of(user)
  .mapN(_ => _.contacts)
  .mapN(_ => _.length)
```

But in this case I kind of used `Try` instead, so `Try.of(() => user.contacts.length)`.

So you know, if you liked `mapN`, copy/paste it from 6.2.2 and make a PR to re-add it.
