### ISSUE TITLE
Help with compose and point free functions.

### ISSUE THREAD

**Issue by martinDlocal** [funfix/funfix.js#126]
Hi!,
thanks a lot for this library, it`s awsome!

I have a question when i want to use composition and [point free](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch05.md#pointfree) style:

```js
import { compose, map } from 'ramda';
import { Some, Option, None } from 'funfix';

const optional = ():Option<number> => Some(2);
const add1 = (n:number):number => n + 1; 

/* map example:
*  const map = fn => mn => mn.map(fn); 
*/

const result = compose(map(add1), optional)();
// same of: optional().map(add1)
```

When I execute it, it works well, but the type inference usually gets complicated.
Is there a better way to do this with funfix?

Thanks a lot!

**Comment by nythrox** [comment]
Hello @martinDlocal, I'm not the owner of the repo and I know this is 2 years later, but in case you are interested, it is possible to get the correct type inference with point-free style. Although it is a bit hacky, it works very well, you can see some examples in [fp-ts](https://github.com/gcanti/fp-ts/) (for static-land) and [purifree](https://github.com/nythrox/purifree) (for fantasy-land). Basically, it works by simulating higher kinded types which typescript doesn't have, gcanti has written an awesome article on it [here](https://medium.com/@gcanti/higher-kinded-types-in-typescript-static-and-fantasy-land-d41c361d0dbe).
