### ISSUE TITLE
Why do you have to create a success option manually with Option<T>.flatmap?

### ISSUE THREAD

**Issue by HIMISOCOOL** [funfix/funfix.js#133]
for Option<T>.flatMap the failure branch returns a None but the success branch only returns the function value
```
if (this._isEmpty) return None
else return f(this.value as A)
```
where as with Map
```
return this._isEmpty ? None : Some(f(this.value as A))
```
The result is boxed.
Is there a reason for this?

**Comment by sledorze** [comment]
@HIMISOCOOL f function taken as param of flatMap already does boxing.
That's standard FP behavior.
The result of both functions map and flatMap are an Option.
