### ISSUE TITLE
Documentation is dead

### ISSUE THREAD

**Issue by MaximeRVY** [funfix/funfix.js#136]
Hi there, 

The documentation is dead :-( 

https://funfix.org/api/core/ 

Error 526.

Thanks

**Comment by alexandru** [comment]
Sorry about that @MaximeRDY, I got a free Pro account from Cloudflare, since they are passing those on open source projects, then went nuts on configuring stuff and apparently I enabled "Full SSL (Strict)", which caused this problem.

Documentation should be back online now.

**Comment by alexandru** [comment]
Enabled an up-time monitor, hopefully it will make me see it sooner.

Thanks for the notice.
