### ISSUE TITLE
Add `uncancelable` for IO

### ISSUE THREAD

**Issue by sledorze** [funfix/funfix.js#138]

**Comment by alexandru** [comment]
👍

**Comment by sledorze** [comment]
@alexandru 
I don't have a lot of free time ATM but can come with that if it fits the requirements (looking for validation here)

So the actions would be:

Create a `StackedUncancelable` in funfix exec that does not nothing.

Implement `uncancellable` as a static (also as a class member?) 
```typescript
  static uncancellable<A>(io: IO<A>) {
    return IO.asyncUnsafe<A>((ctx, cb) => {
      const ec = ctx.scheduler;
      ec.trampoline(() => {
        const conn = stackedUncancelableRef; // stackedUncancelableRef being a singleton instance of StackedUncancelable defined in funfix-effect
        IO.unsafeStart(io, ctx, ioSafeCallback(ec, conn, cb));
      });
    });
    return io;
  }
```

Add the flow definitions (not versed into it, but looks definitely possible)

Everything with tests and frenchy english comments!

**Comment by sledorze** [comment]
@alexandru sorry to bug you, but can you confirm / infirm on the approach?

**Comment by sledorze** [comment]
@alexandru pinging again as I need safe cancellation to hit prod quite soon (not joking).
And would help making it happen, of course.
