### ISSUE TITLE
Is Validated/Validation out of scope for funfix-core

### ISSUE THREAD

**Issue by DavidDudson** [funfix/funfix.js#149]
Just ran into the need for a validated type.
I'm considering creating a PR for this.

Questions I have:

1. Is it beyond the scope of funfix-core?
2. Should we use scalaz (Validation) or cats (Validated) as a base?

**Comment by sledorze** [comment]
@DavidDudson The project does not seems very active - not sure about its future (I hope it will remain active as I'm using it).

In case you badly need to progress, you may look at https://github.com/gcanti/fp-ts which shares the same HKT encoding.

Here's its Validation module:
https://github.com/gcanti/fp-ts/blob/master/src/Validation.ts
