### ISSUE TITLE
Use 7.0.1 funfix version in Angular based on Webpack

### ISSUE THREAD

**Issue by tosun-si** [funfix/funfix.js#155]
Hi, i want to use funfix in a the Angular framework based on Webpack.

After the install of the dependency npm install --save funfix, the dependency is well added in the nodes_modules and package.json.

Then i use, for example, the pattern Option with the following import :

```typescript
import {Option} from "funfix";
```
But i have the following error : 

```typescript
ERROR in node_modules/funfix-core/dist/disjunctions.d.ts(775,14): error TS2416: Property 'value' in type 'TNone' is not assignable to the same property in base type 'Option<never>'.
  Type 'undefined' is not assignable to type 'never'.

**Comment by OliverJAsh** [comment]
See https://github.com/funfix/funfix/issues/122#issuecomment-376089404

**Comment by lvitaly** [comment]
@OliverJAsh basically, `strictNullChecks` can affect other dependencies 🤔
