### ISSUE TITLE
Distribute ES5 instead of ES2015

### ISSUE THREAD

**Issue by OliverJAsh** [funfix/funfix.js#52]
The popular tool webpack uses UglifyJS under the hood, which only works with ES5.

This means that when using webpack to compile and minify an app using funfix, it will fail, because the funfix package is distributed as ES2015.

A workaround is possible: https://stackoverflow.com/a/45088328/5932012

However, it would be good to make this work out of the box for other webpack users. Distributing as ES5 seems to be common practice.

**Comment by OliverJAsh** [comment]
Turns out we don't have a workaround for this afterall: https://github.com/mishoo/UglifyJS2/issues/2333#issuecomment-332439776

**Comment by alexandru** [comment]
Attempted fix by providing separate ES5-compiled modules is released in [version 6.1.0](https://github.com/funfix/funfix/releases/tag/v6.1.0).

**Comment by OliverJAsh** [comment]
Thank you!

**Comment by OliverJAsh** [comment]
I'm just coming back to this in an attempt to add funfix to my application again.

After reading https://github.com/funfix/funfix/pull/55, I'm a bit confused about the current status of the distributed bundles.

As I understand it, there are three distributions:

- `index.js`: ES Modules + ES2015
- `umd.js`: UMD + ?
- `es5.js`: CommonJS + ES5

Is this correct? If so, what is the ECMA version of the `umd` distribution?

I understand `umd.js` is the distribution used in `package.json`'s `main` field. If `umd.js` is not ES5, is there any reason why? (If users want to upgrade to ES Modules or ES2015, they can use the `module` field instead. http://2ality.com/2017/04/setting-up-multi-platform-packages.html#overview)

Perhaps all of this can be documented somewhere.

For context, webpack will happily consume ES Modules—it can use them for tree shaking. The problem is specifically with ES2015 syntax, *excluding ES Modules*, which webpack's Uglify plugin cannot consume.

I appreciate this is fiddly, given the nature of JS. Thank you for your help!

**Comment by alexandru** [comment]
Hi @OliverJAsh,

| File     | Module Format      | Syntax  |
|----------|--------------------|---------|
| index.js | ES Modules         | ES2015  |
| umd.js   | CommonJS / browser | ES5     |
| es5.js   | ES Modules         | ES5     |

[UMD](https://github.com/umdjs/umd) is a "universal" packaging that is meant for both the browser and Node.js, being compatible with CommonJS and AMD. So UMD is basically every other module system that is not ES.

In Node, when you'll `require` something, it's `umd.js` that's going to load. Or if you need to load the library in the browser without any special packaging with Webpack / Rollup. And yes, it's compiled to the lowest common denominator we can support, therefore ES5.

Is there any reason for why you're asking about `umd.js`? Do you suspect that it is not ES5?

What Webpack needs, from what I understood, is ES5 syntax + ES Modules. That's `es5.js`.

This means that in your code you'll need to do ...

```typescript
import { ... } from "funfix-core/dist/es5"

// ... or using the whole library ...

import { ... } from "funfix/dist/es5"
```

**Comment by alexandru** [comment]
I'll be online on Gitter for the next hour if you want to talk.

**Comment by OliverJAsh** [comment]
That clear things up a lot. Thank you.

**Comment by sledorze** [comment]
I'm unsure this is actually working, maybe that's due to a refactor of the project.

es5.js:

```typescript
export * from 'funfix-core';
export * from 'funfix-exec';
export * from 'funfix-effect';
//# sourceMappingURL=es5.js.map
```

would it be?:

```typescript
export * from 'funfix-core/dist/es5';
export * from 'funfix-exec/dist/es5';
export * from 'funfix-effect/dist/es5';
//# sourceMappingURL=es5.js.map
```
