### ISSUE TITLE
Fantasy Land compatibility

### ISSUE THREAD

**Issue by mrdziuban** [funfix/funfix.js#62]
Do you have any plans to make funfix compatible with [Fantasy Land](https://github.com/fantasyland/fantasy-land) for interoperability with other functional libraries like ramda? I believe a lot of the functions for compatibility already exist in funfix, but functions would need to be aliased to conform to the [Fantasy Land prefixed method names](https://github.com/fantasyland/fantasy-land#prefixed-method-names). Thanks for the great library!

**Comment by alexandru** [comment]
@mrdziuban the answer is yes, there are plans. 

But I have to get familiar with Fantasy Land and I'll probably need help for it.

Will leave this ticket open to track the progress made.

**Comment by mrdziuban** [comment]
Thanks @alexandru, I'll keep an eye on this ticket. I'm happy to help where possible though I would need to get more familiar with Fantasy Land as well.

**Comment by alexandru** [comment]
Fantasy-Land compatibility has just landed on master, a pre-release version will get published soon.

**Comment by puffnfresh** [comment]
Fantasy Land spec is violated by things like `Option.of` checking for nulls.
