### ISSUE TITLE
Suggestion: add Option.orUndefined

### ISSUE THREAD

**Issue by OliverJAsh** [funfix/funfix.js#66]
Sometimes an `Option` needs to be serialised to `T | null` or `T | undefined`. We have `Option.orNull` for the former. Could we add `T | undefined` for the latter?

**Comment by alexandru** [comment]
Sure. If you're inclined to submit a PR, I'd like that 😀 if not, I can take care of it, tonight or tomorrow — since it's an easy feature.

**Comment by alexandru** [comment]
Btw, you can also do `.getOrElse(undefined)`, which should give you an `A | undefined` as a result.
